### ISSUE TITLE
COM_GetModDirectory identifier not found

### ISSUE THREAD

**Issue by KaydemonLP** [sapphonie/sdk13-gigalib#15]
It exists in the SDK, however, it's defined in a unintuitive cpp, its header does not include an extern.
`extern const char *COM_GetModDirectory();` should be added to the cpp then, or its function written manually.

**Comment by Nbc66** [comment]
I think it would be easier to just take the existing function and plop it into the lib itself or you can specify that ppl should extern the function when they want to use the lib

**Comment by sapphonie** [comment]
fixed with HACK_COM_GetModDirectory() but it's also no longer used, lol
